### ISSUE TITLE
question about iteration

### ISSUE THREAD

**Issue by aidialogue** [shirley-wu/vdebugger#2]
Hello!You discussed the iteration numbers in paper, but I could not find any parameters related to the iteration counts in the provided code. Does the mention of iteration numbers imply that the infer_critic.py and infer_refine.py need to be executed multiple times?Would you kindly confirm if my understanding is correct? Could you please provide some guidance on how to properly set up and execute these iterations?Thanks！

**Comment by shirley-wu** [comment]
Hello, yes we need to run infer_critic.py and infer_refine.py for multiple times. To save time, we only run the code when it is changed after critic and refinement; that is, when the code is classified as incorrect (so it's necessary to be refined) and the refiner propose a change in the code. I'll update the relevant script next week, but it's pretty straightforward so you can also implement it by yourself

**Comment by shirley-wu** [comment]
Hi, sorry for the late response. I uploaded some helper scripts at https://github.com/shirley-wu/vdebugger/tree/main/vdebugger/iterative_helper. Hope that helps!
