### ISSUE TITLE
maskrcnn error

### ISSUE THREAD

**Issue by aidialogue** [shirley-wu/vdebugger#3]
Hello!I'm currently encountering an ImportError:/lib64/libm.so.6: version `GLIBC_2.29' not found (required by vipergpt/viper-main/GLIP/maskrcnn_benchmark/_C.cpython-310-x86_64-linux-gnu.so)Unfortunately, I do not have sudo privileges on this machine, which prevents me from upgrading the GLIBC version.Have you encountered this issue before?Thank you very much for your time and assistance.

**Comment by shirley-wu** [comment]
Hi, I have not met that issue. It seems to be a library / version issue. I can only throw a few random guesses here: have you compiled GLIP properly? Can you try installing the missing library without sudo, like with pip or conda? Or can you compile with lower versions of other libraries, like torch, so they're compatible with lower-version GLIBC?
