### ISSUE TITLE
About refcoco

### ISSUE THREAD

**Issue by aidialogue** [shirley-wu/vdebugger#4]
Hello!I have a question regarding the evaluation metrics used in your paper. Specifically, in the code snippet:
iou_ = box_iou(p, g).item()  
iou += iou_
if iou_ > 0.7:
    acc += 1
 return iou / max(num_samples, 1), acc / max(num_samples,  1)
Is the RefCOCO score you refer to in the paper the iou / max(num_samples, 1) or acc / max(num_samples, 1)? 
Thank you for your time and help!

**Comment by shirley-wu** [comment]
Hi, sorry I just saw your question. The metrics we report in the paper is IoU, not accuracy.
